#!/bin/bash

# 'Config' for the dotfile repo updater script. Also contains helper functions
# for the time being.
#
# thall.



# VARIABLES/ARRAYS

paths=()
inclusion_list="./inclusions.dat"
target_root_base="${HOME}/dotfiles/"
emacs_target_root="${HOME}/dotfiles/emacs/"


# MSG STRINGS
copied_msg="[INFO] Source is newer. Target updated."
error_target_newer="[ERROR] Target file is newer: Exiting..."
warn_src_trgt_eq="[INFO] Nothing to do: Source and target have identical modification times."
diff_eq_msg="[INFO] Nothing to do: Files up to date."

# HELPERS

function read_paths() {
    if [ -e "$inclusion_list" ]; then
	while IFS= read -r line; do
	    paths+=("$(eval echo "$line")")
	done < "$inclusion_list"
    else
	printf '[ERROR] Could not find inclusion list `%s`\n' "$inclusion_list"
	exit 1
    fi
}

function verify_paths() {
    for path in "${paths[@]}"; do
	if [ -e "$path" ]; then
	    printf 'OK: `%s`\n' "$path"
	else
	    printf '[ERROR] Failed to verify file: `%s`\n' "$path"
	fi
    done


}
